[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线版
;基于https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Mini_Ai.ini

ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=🎯 全球直连,[]PROCESS-NAME,aria2c
ruleset=🎯 全球直连,[]PROCESS-NAME,BitComet
ruleset=🎯 全球直连,[]PROCESS-NAME,fdm
ruleset=🎯 全球直连,[]PROCESS-NAME,NetTransport
ruleset=🎯 全球直连,[]PROCESS-NAME,qbittorrent
ruleset=🎯 全球直连,[]PROCESS-NAME,Thunder
ruleset=🎯 全球直连,[]PROCESS-NAME,transmission-daemon
ruleset=🎯 全球直连,[]PROCESS-NAME,transmission-qt
ruleset=🎯 全球直连,[]PROCESS-NAME,uTorrent
ruleset=🎯 全球直连,[]PROCESS-NAME,WebTorrent
ruleset=🎯 全球直连,[]PROCESS-NAME,Folx
ruleset=🎯 全球直连,[]PROCESS-NAME,Transmission
ruleset=🎯 全球直连,[]PROCESS-NAME,WebTorrent Helper
ruleset=🎯 全球直连,[]PROCESS-NAME,v2ray
ruleset=🎯 全球直连,[]PROCESS-NAME,ss-local
ruleset=🎯 全球直连,[]PROCESS-NAME,ssr-local
ruleset=🎯 全球直连,[]PROCESS-NAME,ss-redir
ruleset=🎯 全球直连,[]PROCESS-NAME,ssr-redir
ruleset=🎯 全球直连,[]PROCESS-NAME,ss-server
ruleset=🎯 全球直连,[]PROCESS-NAME,trojan-go
ruleset=🎯 全球直连,[]PROCESS-NAME,xray
ruleset=🎯 全球直连,[]PROCESS-NAME,hysteria
ruleset=🎯 全球直连,[]PROCESS-NAME,singbox
ruleset=🎯 全球直连,[]PROCESS-NAME,UUBooster
ruleset=🎯 全球直连,[]PROCESS-NAME,uugamebooster
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PrivateTracker.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/godfather1103/custom_openclash_rules/main/fmy/fmy-DIRECT.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/godfather1103/custom_openclash_rules/main/fmy/fmy-REJECT.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
ruleset=✉️ Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=💬 Ai平台,[]DOMAIN-SUFFIX,augmentcode.com
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ClaudeAI.list
ruleset=㊙️ 私密网站,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Dmm.list
ruleset=㊙️ 私密网站,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=㊙️ 私密网站,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pornhub.list
ruleset=㊙️ 私密网站,https://raw.githubusercontent.com/godfather1103/custom_openclash_rules/main/fmy/fmy-Pron.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Amazon.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Hulu.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HuluJapan.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/godfather1103/custom_openclash_rules/main/fmy/fmy-Proxy.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-HK`url-test`(香港|HK)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-SG`url-test`(新加坡|SG)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-US`url-test`(美国|US|🇺🇸|racknerd)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-JP`url-test`(日本|JP)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-TW`url-test`(台湾|TW)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-EU`url-test`(英国|UK|德国|DE|法国|FR|土耳其|TR)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动-ASEAN`url-test`(马来西亚|MY|泰国|TH|新加坡|SG|菲律宾|PH|越南|VN|印度尼西亚|印尼|ID)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]REJECT`[]🚀 节点选择`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=🎬 流媒体`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=💬 Ai平台`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=✉️ Telegram`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=㊙️ 私密网站`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]♻️ 自动-HK`[]♻️ 自动-US`[]♻️ 自动-SG`[]♻️ 自动-JP`[]♻️ 自动-TW`[]♻️ 自动-EU`[]♻️ 自动-ASEAN`[]DIRECT`.*

enable_rule_generator=true
overwrite_original_rules=true
